words = [
    # "DRIVES",
    # "CHEESE",
    # "SCHOOL",
    # "LAPTOP",
    # "LAUGH",
    # "GARDEN",
    # "SUMMER",
    # "WATER",
    # "TREES",
    # "MANAGER",
    # "HAPPY",
    # "HICCUP",
    # "LIGHT",
    "SUNSHINE",
    # "TRAVEL",
]